<?php
/**
 * Created by PhpStorm.
 * User: mirza
 * Date: 6/28/18
 * Time: 5:50 PM
 */

namespace Model\Entity;


use Component\Collection;
use Model\Contract\HasId;

class WorkoutCollection extends Collection implements \Countable
{
    private $statusCode;

    /**
     * @return mixed
     */
    public function getStatusCode()
    {
        return $this->statusCode;
    }

    /**
     * @param mixed $statusCode
     */
    public function setStatusCode($statusCode): void
    {
        $this->statusCode = $statusCode;
    }

    public function buildEntity(): HasId
    {
        // TODO: Implement buildEntity() method.
    }


    public function getIds()
    {
        return parent::getIds(); // TODO: Change the autogenerated stub
    }
}